### ISSUE TITLE
Tree and Node function

### ISSUE THREAD

**Issue by X-Raym** [philipstanislaus/performant-array-to-tree#1]
Hi !
I am new to JavaScript Tree data structure, so sorry if my question is irrelevant,
I wanted to know if you plan usual tree and node method (search for a node, add a child, delete a node...), as describe on the following link for eg ?

https://code.tutsplus.com/articles/data-structures-with-javascript-tree--cms-23393

As far as I undestood I didnt see any other array to tree npm module which embeds such features, and as your script seems more efficient, it could bice to have these !

Thanks for listening :)

**Comment by philipstanislaus** [comment]
Hi, 

thanks for writing, and welcome to the forest ;)

I feel search, deletion and addition of nodes is out of scope for this module for two reasons:

Primarily, I feel this module should keep its small footprint (it has only 0.448 kb right now). This module is used in the browser (where file size matters) and the features you describe might not be needed in many applications. It might be worthwhile to consider to build additional modules for the features you require, which would solve this issue (e. g. [lodash](https://lodash.com/) uses such a modular approach for the same reason).

Secondly, I am hesitant to impose a structure on the items/nodes. At least search needs structure though (e. g. the `data` property in the example you provided). 

Happy to discuss this further.
