### ISSUE TITLE
Add support for parentId = undefined or Integer?

### ISSUE THREAD

**Issue by greatestview** [philipstanislaus/performant-array-to-tree#11]
First, thank you @philipstanislaus for building this nice and helpful tool!

I ran in some issues while trying to use it on a project, which I could track down to these points:
- Items are ignored, if their `parentId` is `undefined`.
- Items are ignored, if their `parentId` is `0`.

Looking at the code, I saw, that you expect IDs to be strings. My project uses Integers with `parentId: 0` for Root-Items. So no surprise it didn’t work out.

Would you mind:
- adding support for Integer IDs?
- allowing `undefined` (= nonexisting) and `0` (Int) as values of parentId in addition to `null`?

I would submit a PR, but I’m not used programming in TypeScript. :) Thank you in advance.

**Comment by philipstanislaus** [comment]
Hey @greatestview sorry for the late reply – this project was a bit out of focus for the last months. 

I have just merged #14, which adds support for `undefined` as root items, and also added integer support in #11 . 

These changes are released in version 1.4.0

**Comment by philipstanislaus** [comment]
Let me know if you need any more support!
