### ISSUE TITLE
Add support for parentId as empty string ("")

### ISSUE THREAD

**Issue by gmw-web** [philipstanislaus/performant-array-to-tree#17]
Somewhat related to #11 .

We have a project in which `id's` are represented as `string`. We run into problems when `parentId === ""` (the items are ignored/the tree is not building). We can solve the issue by replacing all empty strings by `null`, but this is a bit cumbersome.

Would it be possible to support empty strings in addition to `null`, `undefined` and `0`?

We also noticed that there is no output (warnings/errors) in the console when tree building fails. This could help identify problems early on and would be nice to have :)

**Comment by philipstanislaus** [comment]
@gmw-web makes sense, I have added support for empty string parentIds as root objects in https://github.com/philipstanislaus/performant-array-to-tree/releases/tag/v1.6.0 

Could you give me an example how the tree building fails? Thanks!

**Comment by gmw-web** [comment]
Wow, that's quick. Thanks a lot for the quick fix! :)

I exaggerated a bit because tree building doesn't really fail.. In our case an empty tree was returned because `parentId` was an empty string. At first glance this looked like the tree build failed.

What I meant with my 'nice to have' remarks was that it would be great to have some warnings in the console for the following:
- input invalid (does not match config)
- no root node detected, thus no tree is returned
- unable to place node X

**Comment by philipstanislaus** [comment]
@gmw-web understood – that's a good point. 

Tracking orphans has a small runtime penalty though – so I added an option that will trigger an error if orphans are found. 

Released in version https://github.com/philipstanislaus/performant-array-to-tree/releases/tag/v1.7.0

Hope that this is useful for you!
