### ISSUE TITLE
Add multiple parent ids

### ISSUE THREAD

**Issue by hexadeciman** [philipstanislaus/performant-array-to-tree#19]
It would be great to add an option to add a list of parent ids, so that the element gets duplicated and added to the respective parents objects.

**Comment by philipstanislaus** [comment]
Not sure I follow – can you give an example of how the function call and how inputs/outputs would look? 

Thanks!

**Comment by hexadeciman** [comment]
```
const tree = arrayToTree([
    { id: '4', parentId: null, custom: 'abc' },
    { id: '31', parentId: null, custom: '12' },
    { id: '1941', parentId: ['4', '418'], custom: 'de' },
    { id: '1', parentId: ['418'], custom: 'ZZZz' },
    { id: '418', parentId: null, custom: 'ü'},
])
```

result:

```
[
    { data: { id: '4', parentId: null, custom: 'abc' }, children: [
        { data: { id: '1941', parentId: '4', custom: 'de' }, children: [] },
        { data: { id: '31', parentId: '4', custom: '12' }, children: [] },
    ] },
    { data: { id: '418', parentId: null, custom: 'ü'}, children: [
        { data: { id: '1941', parentId: '418', custom: 'de' }, children: [] },
        { data: { id: '1', parentId: '418', custom: 'ZZZz' }, children: [] },
    ] },
]
```

**Comment by philipstanislaus** [comment]
Thanks for the example.

Can you give a bit context which use cases that would cover?

It seems to me like a very special use case that would complicate `performant-array-to-tree` quite a bit.

**Comment by hexadeciman** [comment]
It is a special use case, just thought it would be a nice addition to extend the package usage.

> Can you give a bit context which use cases that would cover?
A structure where a child can be nested in multiple parent, you can imagine it applied to a nested menu for instance.

Feel free to close the issue if you don't think it's relevant.

**Comment by philipstanislaus** [comment]
This issue must have slipped through the cracks – sorry for that. I am not sure that this feature will be widely used, and feel the negative performance impact a potential implementation could have does not make adding this a good trade-off. 

If more users are looking for that feature, I'm happy to re-open this issue.
