### ISSUE TITLE
{ id: ".key" } does not work

### ISSUE THREAD

**Issue by SKFrozenCloud** [philipstanislaus/performant-array-to-tree#31]
Using ".key" as id does not work.

My guess is that the code references the element as item.id and not item[id].
Since ".key" contains a dot it needs to be accessed with item[".key"].

I do not know Typescript but I think this is as an example of accessing with .id compared to [id]:

https://github.com/philipstanislaus/performant-array-to-tree/blob/594f4d1c40d6e4e92918794d682ac8e6f2cb32ae/src/arrayToTree.ts#L57

**Comment by philipstanislaus** [comment]
This is definitely a bug, the reason for this is our support of nested keys, which are separated by dots `.`.

I have published a new release that adds an option `nestedIds`. Set it to `false` and you should not run into this issue anymore. Example test case for reference: https://github.com/philipstanislaus/performant-array-to-tree/blob/9a1f2d2e3423a2bd763a0e41601ab91f6d889adf/src/arrayToTree.spec.ts#L98

Release: 
https://www.npmjs.com/package/performant-array-to-tree/v/1.9.0
https://github.com/philipstanislaus/performant-array-to-tree/releases/tag/v1.9.0
