### ISSUE TITLE
Cross reference array gives an empty array

### ISSUE THREAD

**Issue by kh0ma** [philipstanislaus/performant-array-to-tree#37]
```
var performantArrayToTree = require("performant-array-to-tree")

console.log(performantArrayToTree.arrayToTree([
    { num: "4", ref: "31", custom: "abc" },
    { num: "31", ref: "4", custom: "12" },
  ],
  { id: "num", parentId: "ref", childrenField: "nodes", throwIfOrphans: true }
));

// result = []
```

version: 1.9.1

Actually, I don't have a strong opinion on the expected result from this situation. But it seems strange that the lib silently cut an array. Probably it should be an error?

**Comment by kh0ma** [comment]
Temporary in my project I did it the following way:
- call arrayToTree with a given array
- count entries in Tree
- compare the length of an array vs "length" of Tree

Here we can count on Tree length w/o needs to recalculate it. So will validate it at the end.

Do we care about backward compatibility?

Should it be a config `throwIfCircular: true` similar to `throwIfOrphans: true`?

**Comment by philipstanislaus** [comment]
Sorry for the delay in resolving this.

I just checked out the current code, and realized that this is actually a special case of `throwIfOrphans`, since any items with a circular parent/child relationship would just be a group of orphans that will not be part of the tree.

**Comment by philipstanislaus** [comment]
Released in https://www.npmjs.com/package/performant-array-to-tree/v/1.10.0
