### ISSUE TITLE
ParentId not in the array

### ISSUE THREAD

**Issue by kuehcj** [philipstanislaus/performant-array-to-tree#4]
May I know how do you handle the situation where an item has `parentId` (i.e. it is not `null`) that does not match the `id` of any other items in the array, and therefore the item itself should be considered a root element?

**Comment by philipstanislaus** [comment]
Good question. 

Currently, such "orphans" (items with a parent id that does not match any item in the set) are just ignored. I added a test to show that behavior: 

I feel it would be confusing to add orphans to the root. As an unrelated example: How do you treat people with unknown parents in a pedigree? Do you classify them as original people at the root of your pedigree?

I would change the data structure accordingly. 

Therefore, I'm closing this issue. If you have a strong argument for adding orphans to the root, please reply to this issue so I can re-open it. 

Thanks!

**Comment by kuehcj** [comment]
Hi @philipstanislaus,
It is not that these nodes are orphans that do not have parent. Sometimes it is simply because their parents are excluded from the array. 

For example, with the 3-level tree below,
![image](https://user-images.githubusercontent.com/17485180/62903237-597b0a00-bda5-11e9-9830-8321a0d30299.png)

if the nodes at level 1 are excluded, then the included nodes in the array will be just this:
![image](https://user-images.githubusercontent.com/17485180/62903204-47996700-bda5-11e9-89cf-1d9f755f4452.png)

However, the nodes at level 2 still have parent id even though their parent has been excluded. In this scenario, it actually is valid to regard these nodes at level 2 as new parents.

**Comment by philipstanislaus** [comment]
Understood. I think it makes more sense to have a rootId in that case, e. g. treat `parentId` `418` as root element. Would that solve your problem?
