### ISSUE TITLE
Is there a way to omit children key if there is no child nodes?

### ISSUE THREAD

**Issue by ilyosjon09** [philipstanislaus/performant-array-to-tree#41]

**Comment by Tihomir971** [comment]
Same suggestion

**Comment by philipstanislaus** [comment]
Sorry for the late reply – agree that it's not necessary to have an empty children array, but unfortunately changing this now would be a breaking change for existing library users.

Adding an option would make the package more heavy weight, I would therefore prefer not to implement this. 

If you decide to change this behavior in a fork, please add a link to this issue. Closing this for now.
