### ISSUE TITLE
[Feature Request] Pass type for data property with Generics

### ISSUE THREAD

**Issue by sectsect** [philipstanislaus/performant-array-to-tree#47]
Thanks for your helpful package.

`data` property always returns type `any`.
I think it would be very useful if we could pass type with Generics.

**Comment by philipstanislaus** [comment]
That's right, it's at the moment not properly typed. The challenge is that the key of the data is configurable, and IIRC TypeScript did not support generics powerful enough to support all the configuration options. This might have changed with newer TypeScript versions – would you like to try fixing this and open a PR with your suggestion? 

Would much appreciate that!

**Comment by sectsect** [comment]
@philipstanislaus 
I understand the situation.
This is a problem that should be solved in TypeScript core.
Closing this ticket as it is not a problem with this package.

Thank you.

**Comment by philipstanislaus** [comment]
Thanks @sectsect !
